version: "3.9"

services:
  database:
    image: postgres
    container_name: database_games
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=queries_challenge
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: gamers
    restart: always
    ports: 
      - 3000:3000
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local